name: 'nightly-release'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Clone repository
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: lib/rust

    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 11

    - uses: gradle/gradle-build-action@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - run: |
        python -m pip install cargo-lambda

    # Build your application, tool, artifacts, etc.
    - name: Build
      shell: bash
      run: |
        make -j package

    - uses: actions/upload-artifact@v3
      with:
        name: build-assets
        path: "matano*.sh*"

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/download-artifact@v3
      with:
        name: build-assets

    - name: "Update nightly release"
      if: success()
      uses: pyTooling/Actions/releaser@r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        files: "matano*.sh*"
